### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by twistedjoe** [crossbridge-community/crossbridge#73]
Not so sure we should have followed the flash runtime version for crossbridge.

What if we want to push a bunch of update while the flash version doesn't update? 

We add a .x at the end? If they are not matching because of this then maybe we should just keep the version number separated. 

Also, crossbridge version will always lag behind and make big random jump even when there is nothing new. For example if flash update from, 15 to 18 and in the meantime nothing has been done on crossbridge. There jump in version kinda look weird.

What do you think?

**Comment by vpmedia** [comment]
Hi,
The question is good, maybe it wasn't the best idea to change versioning, but I don't see this one as a major issue, because actually no one is updating CrossBridge. At the time I liked aligning to Adobe AIR SDK and Flash Player versioning ( major version . build number ) because it felt simplifies and clears things a bit more.

**Comment by twistedjoe** [comment]
Yeah, no update means no reason to change it, let's reopen the conversation next "release". I am pretty busy too at the moment, but there is a couple of thing I wanted to do, like some fix to GL2S3D for a future release. I need those in order to port my engine to S3D (some function are still stubbed).
