### ISSUE TITLE
CI build machines

### ISSUE THREAD

**Issue by vpmedia** [crossbridge-community/crossbridge#76]
The project needs a Windows and OSX build machine to test commits / make new releases.
Any chance for this kind of support from any other user?
Jenkins or Teamcity with continuous or scheduled (daily for ex.) builds would be helpful a lot.

**Comment by jasonsturges** [comment]
OS X Mavericks and Yosemite available here, and deep interest in heavy participation with this team.  It would be an honor.

Mac build has a variety of issues.

Travis CI is also failing:

> $ brew install adobe-air-sdk
Error: No available formula for adobe-air-sdk 
Searching formulae...
Searching taps...
homebrew/binary/adobe-air-sdk-flex	homebrew/binary/adobe-air-sdk
The command "brew install adobe-air-sdk" failed and exited with 1 during .

**Comment by twistedjoe** [comment]
Hi, 
Progress is kind of slow since there is not many maintainers and they are busy with other projects, but if you think you can help I can add you in the forum staff group on forum.crossbridge.io and in the crossbridge community group.

I was trying to refactor the build system since there was many problem with the current one, but it's on the back burner at the moment. So setting up  a CI on the current one would be a good idea.

Create an account on forum.crossbridge.io and tell me your username. 
There is a thread on it to report what you are working on if you want to update it. 

More helping hand would not hurt.

**Comment by jasonsturges** [comment]
@twistedjoe forum username: jasonsturges (jason@jasonsturges.com)

That sounds great - thanks!
