### ISSUE TITLE
Crossbridge targeting older flash players (and AIR SDK only comes with v16)

### ISSUE THREAD

**Issue by SuperDisk** [crossbridge-community/crossbridge#78]
AIR SDK only ships with the `playerglobal.swc` file for 16.0. When trying to run the latest samples (no. 5, SWC in this case) in CrossBridge 15.0.0.3, it apparently looks for the old 11.1 and 15.0 playerglobal.swc files but bugs out when it can't find them.

Error: unable to open '/Users/nickf/air_sdk/frameworks/libs/player/15.0/playerglobal.swc'.
/Users/nickf/air_sdk/frameworks/flex-config.xml (line: 47)
        </external-library-path>

Makefile:30: recipe for target 'T05' failed

Other people are having this problem on the internet. I "solved" it temporarily by simply copying the 16.0 directory and renaming it 15.0 and 11.1, but that seems very hacky.

**Comment by twistedjoe** [comment]
You can rename or copy /Users/nickf/air_sdk/frameworks/libs/player/16.0 to /Users/nickf/air_sdk/frameworks/libs/player/15.0 and it should work.

Another solution would be to change the /Users/nickf/air_sdk/frameworks/flex-config.xml  and set it so it use the 16 version.

I gave more detail to somebody in this thread if you need more help: http://forum.crossbridge.io/t/problems-with-compiling-samples/24/10

**Comment by SuperDisk** [comment]
Shouldn't it be added as a patch then to the xml file source?

**Comment by twistedjoe** [comment]
Not really, since the version is not "harcoded" in the xml file. If you check it is passed by parameter. 
Normally, you could have any number of playerglobal version and set it in the command line. (Even though it comes with just one). Maybe you could check how to pass the playerglobal version you want. 
Hopefully it is not harcoded into crossbridge. 
The default is 15.0 since it was the last version at the time the build was done. Next version should have 16 or 17.

**Comment by SuperDisk** [comment]
Cool. The makefiles don't seem to indicate any specific version, they just call the modified GCC. What's the switch to specify a version (and why does it require both 15.0 AND 11.1?)

I take it this project is on a backburner? It's a real shame since it's a cool and great idea. JS + Enscripten is cruddy.

**Comment by twistedjoe** [comment]
Hum I just checked quickly, MXMLC calls in the samples seems to use a custom flex config into the sample folder called .flexConfig.xml (hidden folder on a unix system) And the version is hardcoded to 15.0. So it might be that. I doubt that the gcc call is the problem. Since it use the playerglobal in the toolchain.  So it must be the mxmlc calls. You could change the -load-config+=./../.flexConfig.xml parameter to a custom xml if you want. 

For the backburner thing, yeah, adobe abandoned the project, and  they broke the threads recently with a security fix to flash. 

Though some commits are still made from time to time and it stable enough already to be use on commercial project.

**Comment by SuperDisk** [comment]
Yup, I see it. When is .flexConfig.xml even specified? Is it just loaded implicitly because of its name? In that case, why does running the makefile in one of the subdirectories still (apparently) refer to it?

Thanks for your help, man. :)

**Comment by twistedjoe** [comment]
Np!

It is not loaded implicitly. If you chek the samples some of them call mxlmc like this:

     "$(FLEX)/bin/mxmlc" -load-config+=./../.flexConfig.xml

The makefiles force the use of this specific .flexConfig.xml. 
Though, those are just samples to get you started. In your application (where you'll write your own makefile) you can set it however you want. 
A good way would be to use a default file with a way to pass one as parameter maybe.

**Comment by SuperDisk** [comment]
D'oh! Didn't notice that. 
Well looks like I'm all set to get cracking at using this thing. Cheers.
